name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: go build -i -v .
        env:
          GOARCH: amd64
          GOOS: linux
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: chb3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
